# Generated by Django 4.2.5 on 2023-10-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteupb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Message',
        ),
    ]
